# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: no-commit-to-branch

-   repo: local
    hooks:
    -   id: format-code
        name: format code
        description: check whether modified code is formatted or not
        entry: scrpit/hook/format-code.sh
        language: script

    -   id: lint-md
        name: lint-md
        description: check Chinese doc
        entry: scrpit/hook/lint-md.sh
        language: script
