#ifndef CONFIG_TARGET_H_N17QLW9C
#define CONFIG_TARGET_H_N17QLW9C

// This is copied from i386-softmmu/config-target.h
// apparently, this is auto generated by QEMU build system

/* Automatically generated by create_config - do not modify */
#define TARGET_I386 1
#define TARGET_NAME "i386"
#define TARGET_I386 1
#define CONFIG_XEN 1
#define CONFIG_XEN_PCI_PASSTHROUGH 1
#define CONFIG_KVM 1
#define CONFIG_SOFTMMU 1
#define TARGET_SUPPORTS_MTTCG 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1

#endif /* end of include guard: CONFIG_TARGET_H_N17QLW9C */
