#ifndef CONFIG_TARGET_H_N17QLW9C
#define CONFIG_TARGET_H_N17QLW9C

/* Automatically generated by create_config - do not modify */
#define TARGET_I386 1
#define TARGET_NAME "i386"
#define TARGET_I386 1
#define CONFIG_XEN 1
#define CONFIG_XEN_PCI_PASSTHROUGH 1
#define CONFIG_SOFTMMU 1
#define TARGET_SUPPORTS_MTTCG 1
#define CONFIG_I386_DIS 1
#define CONFIG_I386_DIS 1

#define CONFIG_GUEST_RAM_SIZE (128 * 1024 * 1024)
#define CONFIG_GUEST_BIOS_SIZE (256 * 1024)

#endif /* end of include guard: CONFIG_TARGET_H_N17QLW9C */
