name: compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive --depth=1
    - name: env setup
      run: |
        mkdir -p image
        touch image/bios.bin
        touch image/initrd.bin
        touch image/linuxboot_dma.bin
        touch image/bzImage.bin
    - name: 00
      run: |
        make USE_LIBC=1 ENV_KERNEL=0 USE_GLIB=0 USE_ULIBC_FILE=0
        make clean
    - name: 01
      run: |
        make USE_LIBC=1 ENV_KERNEL=0 USE_GLIB=0 USE_ULIBC_FILE=1
        make clean
    - name: 10
      run: |
        make USE_LIBC=1 ENV_KERNEL=0 USE_GLIB=1 USE_ULIBC_FILE=0
        make clean
    - name: 11
      run: |
        make USE_LIBC=1 ENV_KERNEL=0 USE_GLIB=1 USE_ULIBC_FILE=1
        make clean
